apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: knative-serving
  annotations:
    kapp.k14s.io/change-group: "tce-local/knative-serving"
spec:
  packageRef:
    refName: knative-serving.community.tanzu.vmware.com
    versionSelection:
      constraints: ">0.0.0"
      prereleases: {}
  serviceAccountName: local-knative-default-sa
  values:
  - secretRef:
      name: knative-serving-pkg-values
---
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-pkg-values
  annotations:
    kapp.k14s.io/change-group: "tce-local/knative-serving"
type: Opaque
stringData:
  values.yml:
