apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: grafana
spec:
  packageRef:
    refName: grafana.community.tanzu.vmware.com
    versionSelection:
      constraints: ">=7.5.7"
  serviceAccountName: local-monitoring-default-sa
  values:
  - secretRef:
      name: grafana-pkg-values
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-pkg-values
type: Opaque
stringData:
  values.yml:
