apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: prometheus
spec:
  packageRef:
    refName: prometheus.community.tanzu.vmware.com
    versionSelection:
      constraints: ">=2.27.0"
  serviceAccountName: local-monitoring-default-sa
  values:
  - secretRef:
      name: prometheus-pkg-values
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-pkg-values
type: Opaque
stringData:
  values.yml:
