apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: monitoring.local.community.tanzu.vmware.com.1.0.0
spec:
  refName: monitoring.local.community.tanzu.vmware.com
  version: 1.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/alexandreroman/tce-local-monitoring
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
