#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
ingress:
  enabled: true
  virtual_host_fqdn: #@ "prometheus.{}".format(data.values.local.domain)
  prometheus_prefix: "/"
  alertmanager_prefix: "/alertmanager/"
  prometheusServicePort: 80
  alertmanagerServicePort: 80
#@ end

#@overlay/match by=overlay.subset({"metadata":{"name": "prometheus-pkg-values"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
