apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/additions/metrics-server
  contents:
  - path: .
    git:
      url: https://github.com/vmware-tanzu/community-edition
      ref: v0.10.0
    newRootPath: addons/packages/metrics-server
    includePaths:
    - addons/packages/metrics-server/metadata.yaml
    - addons/packages/metrics-server/0.5.1/package.yaml
