apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  annotations:
    kapp.k14s.io/change-group: "tce-local/cert-manager"
spec:
  packageRef:
    refName: cert-manager.community.tanzu.vmware.com
    versionSelection:
      constraints: ">0.0.0"
      prereleases: {}
  serviceAccountName: local-core-default-sa
