apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  annotations:
    kapp.k14s.io/change-group: "tce-local/contour"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tce-local/cert-manager"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tce-local/cert-manager"
spec:
  packageRef:
    refName: contour.community.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.18.1"
  serviceAccountName: local-core-default-sa
  values:
  - secretRef:
      name: contour-pkg-values
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-pkg-values
  annotations:
    kapp.k14s.io/change-group: "tce-local/contour"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tce-local/cert-manager"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tce-local/cert-manager"
type: Opaque
stringData:
  values.yml: |-
    namespace: contour
    contour:
      replicas: 1
    envoy:
      service:
        type: ClusterIP
      hostPorts:
        enable: true
    certificates:
      useCertManager: true
