apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
spec:
  packageRef:
    refName: contour.community.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.18.1"
  serviceAccountName: local-core-default-sa
  values:
  - secretRef:
      name: contour-pkg-values
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-pkg-values
type: Opaque
stringData:
  values.yml: |-
    namespace: contour
    contour:
      replicas: 1
    envoy:
      service:
        type: ClusterIP
      hostPorts:
        enable: true
    certificates:
      useCertManager: true
