name: Build and deploy package repository

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: actions/checkout@v2

    - name: Log in to the container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Deploy package repository
      run: make push
